version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="imx_market_db"
    ports:
      - 27017:27017
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"