alchemy:
  apiKey: 'exampleApiKey'
database:
  host: 'localhost'
  port: 27017
  name: 'imx_market_db'
network:
  name: 'mainnet'
  chainId: 1
  apiBasePath: 'https://api.x.immutable.com'
  coreContractAddress: '0x5FDCCA53617f4d2b9134B29090C87D01058e27e9'
  registrationContractAddress: '0x72a06bf2a1CE5e39cBA06c0CAb824960B587d64c'
redis:
  host: 'localhost'
  port: 6379